We will use already built token embeddings <br/>
[word2vec-google-news-300](https://huggingface.co/fse/word2vec-google-news-300)<br/>
Pre-trained vectors trained on a part of the Google News dataset (about 100 billion words). The model contains 300-dimensional vectors for 3 million words and phrases. The phrases were obtained using a simple data-driven approach described in 'Distributed Representations of Words and Phrases and their Compositionality'

In [1]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.0/24.0 MB 12.1 MB/s  0:00:01 eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.4/30.4 MB 9.2 MB/s  0:00:03 eta 0:00:01m
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.2
    Uninstalling scipy-1.15.2:
      Successfully uninstalled scipy-1.15.2━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [scipy]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [gensim]2m2/3 [gensim]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yolov5 7.0.14 requires huggingface-hub<0.25.0,>=0.12.0, but you have huggingface-hub 0.33.4 which is incompatible.


In [ ]:
# import gensim.downloader as api
# Uncomment the code when downloading model directly from web
# model = api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
# Save the model into gensim's native format
# model.save("word2vec-google-news-300.model")


In [2]:
# Load the model from file
from gensim.models import KeyedVectors
model = KeyedVectors.load("word2vec-google-news-300.model")

In [3]:
# Example of word as a vector
word_vector = model

# Let us look how a vector for the word 'computer' looks like
print(word_vector['computer'])

[ 1.07421875e-01 -2.01171875e-01  1.23046875e-01  2.11914062e-01
 -9.13085938e-02  2.16796875e-01 -1.31835938e-01  8.30078125e-02
  2.02148438e-01  4.78515625e-02  3.66210938e-02 -2.45361328e-02
  2.39257812e-02 -1.60156250e-01 -2.61230469e-02  9.71679688e-02
 -6.34765625e-02  1.84570312e-01  1.70898438e-01 -1.63085938e-01
 -1.09375000e-01  1.49414062e-01 -4.65393066e-04  9.61914062e-02
  1.68945312e-01  2.60925293e-03  8.93554688e-02  6.49414062e-02
  3.56445312e-02 -6.93359375e-02 -1.46484375e-01 -1.21093750e-01
 -2.27539062e-01  2.45361328e-02 -1.24511719e-01 -3.18359375e-01
 -2.20703125e-01  1.30859375e-01  3.66210938e-02 -3.63769531e-02
 -1.13281250e-01  1.95312500e-01  9.76562500e-02  1.26953125e-01
  6.59179688e-02  6.93359375e-02  1.02539062e-02  1.75781250e-01
 -1.68945312e-01  1.21307373e-03 -2.98828125e-01 -1.15234375e-01
  5.66406250e-02 -1.77734375e-01 -2.08984375e-01  1.76757812e-01
  2.38037109e-02 -2.57812500e-01 -4.46777344e-02  1.88476562e-01
  5.51757812e-02  5.02929

In [6]:
type(word_vector)

gensim.models.keyedvectors.KeyedVectors

In [7]:
print(word_vector['computer'].shape)

(300,)


In [11]:
# Let's see the semantics meaning between words that is kept in these vectors
# King + Woman - Man = ??? (similar to queen)
print(word_vector.most_similar(positive=['king', 'woman'], negative=['man'], topn=10))

[('queen', 0.7118192911148071), ('monarch', 0.6189674735069275), ('princess', 0.5902431011199951), ('crown_prince', 0.5499460697174072), ('prince', 0.5377321243286133), ('kings', 0.5236844420433044), ('Queen_Consort', 0.5235945582389832), ('queens', 0.5181134343147278), ('sultan', 0.5098593235015869), ('monarchy', 0.5087411403656006)]


In [13]:
print(word_vector.most_similar(positive=['prince', 'girl'], negative=['boy'], topn=2))

[('princess', 0.7421581149101257), ('duchess', 0.6354914307594299)]


In [9]:
# Check for similarity between a few pair of words
print(word_vector.similarity('man', 'woman'))
print(word_vector.similarity('king', 'queen'))
print(word_vector.similarity('you', 'me'))
print(word_vector.similarity('her', 'him'))
print(word_vector.similarity('grandpa', 'grandma'))
print(word_vector.similarity('tv', 'radio'))
print(word_vector.similarity('school','college'))

0.76640123
0.6510956
0.5679825
0.48621917
0.77633655
0.43638504
0.6081898


In [12]:
# Most similar words
print(word_vector.most_similar('elephant', topn=5))


[('elephants', 0.7806671261787415), ('rhino', 0.678035318851471), ('pachyderm', 0.6761021018028259), ('tiger', 0.6681443452835083), ('rhinoceros', 0.6430983543395996)]


In [17]:
# Similarity between vectors
# The more the distance between magnitude of vectors, the more dissimilarity between the words
import numpy as np

word1 = 'man'
word2 = 'woman'

vector_diff1 = model[word1] - model[word2]

magnitude_diff1 = np.linalg.norm(vector_diff1)

print(f'Magnitude diff between {word1} and {word2} is {magnitude_diff1:.2f}')

word1 = 'day'
word2 = 'night'

vector_diff1 = model[word1] - model[word2]

magnitude_diff1 = np.linalg.norm(vector_diff1)

print(f'Magnitude diff between {word1} and {word2} is {magnitude_diff1:.2f}')

word1 = 'paper'
word2 = 'cloth'

vector_diff1 = model[word1] - model[word2]

magnitude_diff1 = np.linalg.norm(vector_diff1)

print(f'Magnitude diff between {word1} and {word2} is {magnitude_diff1:.2f}')

Magnitude diff between man and woman is 1.73
Magnitude diff between day and night is 2.01
Magnitude diff between paper and cloth is 3.08


## CREATING TOKEN EMBEDDINGS

In [18]:
import torch
input_ids = torch.tensor([2,3,5,1])

In [22]:
vocab_size = 6
output_dim = 3
torch.manual_seed(100)

embedding_matrix = torch.nn.Embedding(vocab_size, output_dim)

print(embedding_matrix)
print(embedding_matrix.weight)

Embedding(6, 3)
Parameter containing:
tensor([[ 0.1268,  1.3564, -0.0247],
        [-0.8466,  0.0293, -0.5721],
        [-1.2546,  0.0486,  0.2753],
        [-2.1550, -0.7116,  0.0575],
        [ 0.6263, -1.7736, -0.2205],
        [ 2.7467, -1.0480,  1.1239]], requires_grad=True)


In [23]:
print(embedding_matrix(torch.tensor([4])))

tensor([[ 0.6263, -1.7736, -0.2205]], grad_fn=<EmbeddingBackward0>)


In [24]:
print(embedding_matrix(input_ids))

tensor([[-1.2546,  0.0486,  0.2753],
        [-2.1550, -0.7116,  0.0575],
        [ 2.7467, -1.0480,  1.1239],
        [-0.8466,  0.0293, -0.5721]], grad_fn=<EmbeddingBackward0>)
